### ISSUE TITLE
能否看一下这个报错的原因

### ISSUE THREAD

**Issue by zhujinle** [Murlors/QCBL_Report_Print_Automation#1]
### 首先感谢dalao写出这个脚本orz
我在运行.exe文件的时候发现Edge的Driver版本对不上，遂改为运行原始.py脚本，不料出现Simple GUI的报错，百度无果只好前来求助
环境是Anaconda搭的，之前公选课配置的环境现在继续使用，python 3.9安装了所有需要的库
![image](https://user-images.githubusercontent.com/32472522/172374509-6131c478-cd63-4d73-b593-92c0cc625913.png)

**Comment by Murlors** [comment]
可能是Edge的原因，之前上机课我用机房里的Pycharm也报了这个错，原因暂时还不知道
换用Firefox就没有这个错误了

**Comment by Murlors** [comment]
是因为edge的webdrive版本过低，导致打开浏览器失败，进而导致窗口的初始化失败，所以会报这个错误，现在稍微做了些修改，浏览器打开失败会直接闪退（之后会用try except写个弹窗这样子）

**Comment by zhujinle** [comment]
现在重新pull了一下，这一版是可以用的。
我觉得这个问题还是蛮奇怪的，昨天其实试过替换edgedriver，从100替换到了102，也测试过了webdriver是匹配的，但是会报这个错。
照着报错加入finalize=True这一段也试过了，加上去窗口会马上马上闪退return 1，因为太晚了没去调试🤣
之前感觉可能是driver升级了具体的语句用法改变了，但是看了下你修改的代码，感觉对于edge的修改不多，这东西又莫名其妙地好了，蛮奇怪的🤣
还是非常感谢有这么一个小工具的，在线膜拜%%%

---

## orz
